---
deployment:
  tasks:
    - export DEPLOYPATH=/home/laprovic/public_html/
    - /bin/cp -a ./. $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    # --- LÍNEAS ACTUALIZADAS PARA INSERTAR EL HASH EN EL H1 ---
    - export GIT_HASH=$(git rev-parse --short HEAD)
    - /bin/sed -i "s|<span id=\"version-indicator\"></span>|<span id=\"version-indicator\">– ${GIT_HASH}</span>|g" $DEPLOYPATH/index.html